### ISSUE TITLE
Not-OK status from backend does not trigger error callback

### ISSUE THREAD

**Issue by smoorsausje** [ngx-grpc/ngx-grpc#4] opened 2020-02-06 06:50 UTC
We are trying to migrate to the `ngx-grpc` package for our angular app.
Before we were using the `improbable-eng/grpc-web` one. That one has worked fine for us, outside of the lack of interceptors and observables.
Your package seems to fix both those shortcomings, so we are extremely happy with it.

There is just one thing we are having trouble with at the moment.
We are using the `grpc-status` trailer to send validation errors to the frontend. However this does not seem to work with ngx-grpc.

We expect the `error` callback to trigger when we put any grpc status code that is not status 0 `OK`.

Typescript service call:
```ts
this.myService
  .myRpcMethod({} as myRequest)
  .subscribe(
	response => {
	  // This will only trigger when I give a clean response without status code
	},
	error => {
	  // This will only trigger when there is some HTTP layer error (timeout, internal server error, etc)
          // We expect this to also trigger when grpc-status is not 0, otherwise it is not possible to get the status code/message at all
	},
	() => {
	  // This will trigger in all cases where response or error has triggered (as expected)
	}
  );
```

Our .NET backend implementation:
```cs
public override async Task<EmptyResponse> MyRpcMethod(MyRequest request, ServerCallContext context)
{
	context.Status = new Status(StatusCode.NotFound, "Not found");

	return new EmptyResponse
	{
		// Nothing in here
	};
}
```
When we throw a `RpcException` we get a similar result:
```cs
public override async Task<EmptyResponse> MyRpcMethod(MyRequest request, ServerCallContext context)
{
	var status = new Status(StatusCode.NotFound, "Not found");
        throw new RpcException(status);
}
```
When we throw any other exception, then the error does trigger, but then the grpc-status is lost.

Our environment is as follows:
- Angular 8 app
- Ambassador Edge Stack 1.1 (which has Envoy 1.12.1 built-in)
- .NET core 3.0 microservices
- Kubernetes cluster

**Comment by smnbbrv** [comment] 2020-02-06 08:47
Hi @smoorsausje 

currently the observable replicates the original grpc-web error handling:

https://github.com/ngx-grpc/ngx-grpc/blob/81606b3993797f036013168ed2113fbae7954f0d/projects/core/src/lib/grpc-standard-client.ts#L44

I'll try to further investigate this

**Comment by smoorsausje** [comment] 2020-02-06 13:31
Thanks @smnbbrv 

We have busted our heads on the code, trying to find out where in the chain it is going wrong.
So far we think either the trailer is not parsed correctly, or the observable gets completed before the error callback gets triggered.

Sadly we have no way of verifying this easily, so I hope that you are able to find something.

**Comment by smnbbrv** [comment] 2020-02-06 13:59
That's actually weird. Just for the sake of completeness: do you use envoy as a proxy?

**Comment by smoorsausje** [comment] 2020-02-06 16:29
Yes, we use Ambassador, which has Envoy built-in.

**Comment by smnbbrv** [comment] 2020-02-17 20:29
Hi @smoorsausje 

I started to debug your issue around a week ago and to the big surprise could reproduce a similar issue with server streaming. It appeared that grpc-web has some weird decisions and inconsistencies between its methods. While looking for a solution I... rewrote a lot of things and created some breaking changes. Again.

I would kindly ask you to try with the latest (0.3.0 and 0.6.0) versions of packages whether things got changed.

If not, please try to reproduce the issue you have using the fresh new example https://github.com/ngx-grpc/ngx-grpc#example

**Comment by smnbbrv** [comment] 2020-02-17 20:30
Missclicked the button, sorry.

**Comment by smoorsausje** [comment] 2020-02-18 09:26
Hey @smnbbrv
Thanks a lot for your help!!

I was able to implement a request validation interceptor using the new scheme.
From what I could test I've noticed that the error is somehow not passed through properly through the gRPC-Web.

When I use BloomRPC for a request I can get an error response just fine, for example:
```
{
  "error": "9 FAILED_PRECONDITION: No validator was found"
}
```
But this error is never passed through to the angular frontend.

I have a feeling that the gRPC-Web implementation that you are using for this package is somehow not compatible with my configuration. Could this be?

We were using the improbable-eng implementation before, in which the error statuses did work just fine for us.
https://github.com/improbable-eng/grpc-web

---

I wasn't able to get your example to work sadly. Some python errors occured while doing the `npm ci` command:

```
> fsevents@1.2.11 install D:\LocalDevelop\GitHub\ngx-grpc\node_modules\webpack-dev-server\node_modules\fsevents
> node-gyp rebuild


D:\LocalDevelop\GitHub\ngx-grpc\node_modules\webpack-dev-server\node_modules\fsevents>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.1.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [
gyp info spawn args   'C:\\Program ' +
gyp info spawn args     'Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\LocalDevelop\\GitHub\\ngx-grpc\\node_modules\\webpack-dev-server\\node_modules\\fsevents\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\wilko.smoors.ECH\\.node-gyp\\12.1.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\wilko.smoors.ECH\\.node-gyp\\12.1.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program ' +
gyp info spawn args     'Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\wilko.smoors.ECH\\.node-gyp\\12.1.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\LocalDevelop\\GitHub\\ngx-grpc\\node_modules\\webpack-dev-server\\node_modules\\fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\LocalDevelop\\GitHub\\ngx-grpc\\node_modules\\webpack-dev-server\\node_modules\\fsevents\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2019, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1778, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1731, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\LocalDevelop\GitHub\ngx-grpc\node_modules\webpack-dev-server\node_modules\fsevents
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> fsevents@1.2.11 install D:\LocalDevelop\GitHub\ngx-grpc\node_modules\watchpack\node_modules\fsevents
> node-gyp rebuild


D:\LocalDevelop\GitHub\ngx-grpc\node_modules\watchpack\node_modules\fsevents>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.1.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [
gyp info spawn args   'C:\\Program ' +
gyp info spawn args     'Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\LocalDevelop\\GitHub\\ngx-grpc\\node_modules\\watchpack\\node_modules\\fsevents\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\wilko.smoors.ECH\\.node-gyp\\12.1.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\wilko.smoors.ECH\\.node-gyp\\12.1.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program ' +
gyp info spawn args     'Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\wilko.smoors.ECH\\.node-gyp\\12.1.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\LocalDevelop\\GitHub\\ngx-grpc\\node_modules\\watchpack\\node_modules\\fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\LocalDevelop\\GitHub\\ngx-grpc\\node_modules\\watchpack\\node_modules\\fsevents\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2019, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1778, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1731, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\LocalDevelop\GitHub\ngx-grpc\node_modules\watchpack\node_modules\fsevents
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> core-js@3.6.0 postinstall D:\LocalDevelop\GitHub\ngx-grpc\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.10 postinstall D:\LocalDevelop\GitHub\ngx-grpc\node_modules\karma\node_modules\core-js
> node postinstall || echo "ignore"


> fsevents@1.2.9 install D:\LocalDevelop\GitHub\ngx-grpc\node_modules\karma\node_modules\fsevents
> node install


> grpc@1.24.2 install D:\LocalDevelop\GitHub\ngx-grpc\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.14.0
node-pre-gyp info using node@12.1.0 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "D:\LocalDevelop\GitHub\ngx-grpc\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp http 200 https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp info install unpacking node-v72-win32-x64-unknown/grpc_node.node
node-pre-gyp info tarball done parsing tarball
[grpc] Success: "D:\LocalDevelop\GitHub\ngx-grpc\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node" is installed via remote
node-pre-gyp info ok

> @angular/cli@9.0.2 postinstall D:\LocalDevelop\GitHub\ngx-grpc\node_modules\@angular\cli
> node ./bin/postinstall/script.js

added 1788 packages in 30.963s
```

**Comment by smnbbrv** [comment] 2020-02-18 10:08
> I have a feeling that the gRPC-Web implementation that you are using for this package is somehow not compatible with my configuration. Could this be?

Well, it's the official one from Google. So, yes :D It has some problems and downsides, e.g. unlike improbable-eng implementation they don't use websocket for streaming etc.

However, the choice is not that big anyway, what's used is already used.

Unfortunately I'm not anyhow familiar with .net and its gRPC implementation.

Could you check issues that could be similar / related on grpc-web?

https://github.com/grpc/grpc-web/issues/343
https://github.com/grpc/grpc-web/issues/415

About the installation error: the error comes from fs-events which is webpack (hence angular cli) optional dependency and works on MacosX only; which is funny because they constantly have a similar issue some years ago.

Did you try to ignore this error and still run the example? I think it should work anyway.

**Comment by smnbbrv** [comment] 2020-02-18 10:11
Btw would be helpful if you post the response headers (screenshot?) of the error response that is not treated as expected.

**Comment by smoorsausje** [comment] 2020-02-20 06:46
> Could you check issues that could be similar / related on grpc-web?

It seems 415 is very similar to the problem we are having, nice find!
I asked for the solution they found, so I hope they will respond.

> Did you try to ignore this error and still run the example? I think it should work anyway.

Yeah, but then I get the following errors:
```cmd
> @ examples:basic D:\LocalDevelop\GitHub\ngx-grpc
> ng serve basic-example

0% compiling
Compiling @angular/core : es2015 as esm2015

Compiling @angular/common : es2015 as esm2015

Compiling @angular/platform-browser : es2015 as esm2015

Compiling @angular/platform-browser-dynamic : es2015 as esm2015

Compiling @angular/forms : es2015 as esm2015

Compiling @angular/cdk/keycodes : es2015 as esm2015

Compiling @angular/cdk/platform : es2015 as esm2015

Compiling @angular/cdk/observers : es2015 as esm2015

Compiling @angular/cdk/a11y : es2015 as esm2015

Compiling @angular/cdk/bidi : es2015 as esm2015

Compiling @angular/animations : es2015 as esm2015

Compiling @angular/animations/browser : es2015 as esm2015

Compiling @angular/platform-browser/animations : es2015 as esm2015

Compiling @angular/material/core : es2015 as esm2015

Compiling @angular/material/button : es2015 as esm2015

Compiling @angular/common/http : es2015 as esm2015

Compiling @angular/material/icon : es2015 as esm2015

Compiling @angular/cdk/collections : es2015 as esm2015

Compiling @angular/material/divider : es2015 as esm2015

Compiling @angular/material/list : es2015 as esm2015

Compiling @angular/material/slide-toggle : es2015 as esm2015

Compiling @angular/material/toolbar : es2015 as esm2015

chunk {main} main.js, main.js.map (main) 2.04 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 700 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 181 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 341 kB [initial] [rendered]
Date: 2020-02-20T06:35:29.448Z - Hash: cef70c8b7c0b71111de6 - Time: 36368ms

ERROR in examples/basic-example/src/proto/echo.pbconf.ts:7:36 - error TS2307: Cannot find module '@ngx-grpc/common'.

7 import { GrpcClientSettings } from '@ngx-grpc/common';
                                     ~~~~~~~~~~~~~~~~~~
examples/basic-example/src/proto/echo.pb.ts:6:47 - error TS2307: Cannot find module '@ngx-grpc/common'.

6 import { GrpcMessage, RecursivePartial } from '@ngx-grpc/common';
                                                ~~~~~~~~~~~~~~~~~~
examples/basic-example/src/proto/echo.pbsc.ts:13:8 - error TS2307: Cannot find module '@ngx-grpc/common'.

13 } from '@ngx-grpc/common';
          ~~~~~~~~~~~~~~~~~~
examples/basic-example/src/proto/echo.pbsc.ts:19:8 - error TS2307: Cannot find module '@ngx-grpc/core'.

19 } from '@ngx-grpc/core';
          ~~~~~~~~~~~~~~~~
examples/basic-example/src/app/app.component.ts:2:44 - error TS2307: Cannot find module '@ngx-grpc/common'.

2 import { GrpcEvent, GrpcStatusEvent } from '@ngx-grpc/common';
                                             ~~~~~~~~~~~~~~~~~~
examples/basic-example/src/app/app.module.ts:10:64 - error TS2307: Cannot find module '@ngx-grpc/core'.

10 import { GrpcStandardClientFactory, GRPC_CLIENT_FACTORY } from '@ngx-grpc/core';
                                                                  ~~~~~~~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2020-02-20T06:35:34.366Z - Hash: a90963c4501bd8bdbe77
2 unchanged chunks
chunk {main} main.js, main.js.map (main) 43.4 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 140 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.3 MB [initial] [rendered]
Time: 4397ms

ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve '@ngx-grpc/common' in 'D:\LocalDevelop\GitHub\ngx-grpc\examples\basic-example\src\app'
ERROR in ./src/proto/echo.pbsc.ts
Module not found: Error: Can't resolve '@ngx-grpc/common' in 'D:\LocalDevelop\GitHub\ngx-grpc\examples\basic-example\src\proto'
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '@ngx-grpc/core' in 'D:\LocalDevelop\GitHub\ngx-grpc\examples\basic-example\src\app'
ERROR in ./src/proto/echo.pbsc.ts
Module not found: Error: Can't resolve '@ngx-grpc/core' in 'D:\LocalDevelop\GitHub\ngx-grpc\examples\basic-example\src\proto'

    ERROR in examples/basic-example/src/proto/echo.pbconf.ts:7:36 - error TS2307: Cannot find module '@ngx-grpc/common'.

    7 import { GrpcClientSettings } from '@ngx-grpc/common';
                                         ~~~~~~~~~~~~~~~~~~
    examples/basic-example/src/proto/echo.pb.ts:6:47 - error TS2307: Cannot find module '@ngx-grpc/common'.

    6 import { GrpcMessage, RecursivePartial } from '@ngx-grpc/common';
                                                    ~~~~~~~~~~~~~~~~~~
    examples/basic-example/src/proto/echo.pbsc.ts:13:8 - error TS2307: Cannot find module '@ngx-grpc/common'.

    13 } from '@ngx-grpc/common';
              ~~~~~~~~~~~~~~~~~~
    examples/basic-example/src/proto/echo.pbsc.ts:19:8 - error TS2307: Cannot find module '@ngx-grpc/core'.

    19 } from '@ngx-grpc/core';
              ~~~~~~~~~~~~~~~~
    examples/basic-example/src/app/app.component.ts:2:44 - error TS2307: Cannot find module '@ngx-grpc/common'.

    2 import { GrpcEvent, GrpcStatusEvent } from '@ngx-grpc/common';
                                                 ~~~~~~~~~~~~~~~~~~
    examples/basic-example/src/app/app.module.ts:10:64 - error TS2307: Cannot find module '@ngx-grpc/core'.

    10 import { GrpcStandardClientFactory, GRPC_CLIENT_FACTORY } from '@ngx-grpc/core';
```

**Comment by smnbbrv** [comment] 2020-02-24 08:00
That's my bad.

You'd need to run `npm run build` first to run the example. I need to add it to the README as well...

**Comment by vs102000** [comment] 2020-04-07 18:21
Had the same issue. Could fix it by adding expose headers (doing grpc-web directly from asp.net core 3.1). My cors setup is:

app.UseCors(
                options => options.SetIsOriginAllowed(x => _ = true).AllowAnyMethod().AllowAnyHeader()
                    .AllowCredentials()
                    .WithExposedHeaders("X-User-Agent", "X-Grpc-Web", "content-type", "x-grpc-web", "x-user-agent",
                        "grpc-status", "grpc-message") // <-- this is important
                    .Build()
            );

without "grpc-status", "grpc-message" which I had before, I never got the callback. With the two fields added, everything works as expected. If you running envoy / ambassador instead, check also cors topic.
Hope that helps...

**Comment by smnbbrv** [comment] 2020-09-14 10:34
Closing because this issue belongs to grpc-web library.

**Closed by smnbbrv** 2020-09-14 10:34 UTC
