### ISSUE TITLE
@ngx-grpc/worker: No exported member 'Error' in grpc-web

### ISSUE THREAD

**Issue by mrtn123456** [ngx-grpc/ngx-grpc#70] opened 2021-10-28 08:59 UTC
Hi,
I have an issue using @ngx-grpc/worker 2.4.0 together with grpc-web 1.3.0
    
    Error: node_modules/@ngx-grpc/worker/lib/api.d.ts:1:10 - error TS2305: Module '"grpc-web"' has no exported member 'Error'.
    1 import { Error, Metadata, Status } from 'grpc-web';

According to Github history, the exported member "Error" was renamed to "RpcError" recently. After manually changing it to "RpcError" in the `api.d.ts` file everything works fine.

**Comment by smnbbrv** [comment] 2022-03-01 22:20
Thank you for reporting.

The issue is fixed in v3.0.0, see [CHANGELOG](https://github.com/ngx-grpc/ngx-grpc/blob/master/CHANGELOG.md#300-2022-03-01) for details

**Closed by smnbbrv** 2022-03-01 22:20 UTC
