### ISSUE TITLE
client receives all the messages at once when using server-side streaming?

### ISSUE THREAD

**Issue by sfariv** [ngx-grpc/ngx-grpc#60] opened 2021-06-10 00:54 UTC
Hi, I was wondering if that's still a expected behavior I am seeing?
`client receives all the messages at once when using server-side streaming`

I noticed this feature was a WAI back in 2019
https://grpc.io/blog/state-of-grpc-web/#f20

I was wondering if this is still not supported?

**Comment by smnbbrv** [comment] 2021-06-11 04:59
This all depends on what client implementation you are using. If this issue persists try to contact the client library maintainers

**Comment by sfariv** [comment] 2021-06-12 09:37
Thanks for the answers,

I am not sure what you mean by client implementation? could you elaborate more? I am following your example @smnbbrv and it's still not working for me. my code is using grpc-web-client.

**Comment by smnbbrv** [comment] 2021-06-12 11:16
By client implementation I mean packages grpc-web or @improbable-eng/grpc-web . This project is just a middleware that is adapted for these libs with corresponding packages.

The connection itself is implemented by the client lib and issues there are very hard to debug. It is almost impossible to say what is particularly wrong in your implementation without seeing and debugging the whole project and infrastructure; and, as being said above, is not a subject of ngx-grpc.

If you however will be able to find the issue on this side, it should be fixed of course.

**Comment by smnbbrv** [comment] 2022-03-01 21:39
As long as the issue is not active anymore I close it. Please feel free to reopen in case it can be reproduced

**Closed by smnbbrv** 2022-03-01 21:39 UTC
